language: ruby
sudo: false
rvm:
- 2.0.0
- 2.1
- 2.2
- 2.3.1
script:
- bundle install
- bundle exec rake spec
- '[[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && ( bundle exec rake spec:integration
  ) || ( echo "Testing PR - No integration tests available")'
deploy:
  provider: rubygems
  api_key:
    secure: DoX3w48gRyhDM1o1OLvtWsTi8ehLIarIsErzg/UlNRoLacQt5l5UzwD+u6wqsCEr4+c2uAHNahafpnw/j1rPG3LBPIXOK5A0SYbjovlckutiAC0330Q4PHwOZb73AFN1DG5JTeg4/fguEjdsEBdZObF7mh5gBMBQtNjo1Fos+4w=
  gemspec: mailgun.gemspec
  on:
    tags: true
    condition: "$TRAVIS_RUBY_VERSION == 2.3.1"
notifications:
  slack:
    rooms:
      secure: G4iBtDfFGeryQslfrKZK4hSPikOy9y3SDnpzwmN8SoB0uIAWE2mLfMUJZonKm7yoz+DbPU0u3c1SwiMLwHkXZhPdnJdC1fb1DpicXnVgGZYdiLGiY+OAwkvcBE9p3piWhpwigTjvmSqTaNSRL/VLhG4qwQbHU0fTl1M1zwU4e6c=
