# frozen_string_literal: true

module Mailgun
  # A Mailgun::ApiKeys object is a simple CRUD interface to Mailgun Api Keys.
  # Uses Mailgun
  class ApiKeys
    include ApiVersionChecker

    # Public creates a new Mailgun::ApiKeys instance.
    #   Defaults to Mailgun::Client
    def initialize(client = Mailgun::Client.new(Mailgun.api_key, Mailgun.api_host || 'api.mailgun.net', 'v1'))
      @client = client
    end

    # Public: List Mailgun API keys
    #
    # domain_name - [String] Domain name filter for domain keys
    # kind        - [String] Key kind filter
    #
    # Retrieve filtered api keys.
    def list
      res = @client.get('keys')
      res.to_h['items']
    end

    # Public: Create Mailgun API key

    # options - [Hash] of
    #   domain_name - [String] Web domain to associate with the key, for keys of 'domain' kind
    #   kind        - [String] Type of API key ('domain', 'user', or 'web'). Defaults to 'user' if not provided.
    #   description - [String] Key description
    #   expiration  - [String] Key lifetime in seconds, must be greater than 0 if set
    #   role        - [String] Key role ('admin', 'basic' [use in place of analyst],
    #                          'sending' [use with keys of domain kind], or 'developer')
    #   user_id     - [String] API Key user's string user ID; should be provided for all keys of 'web' kind
    #   user_name   - [String] API Key user's name
    #   email       - [String] API Key user's email address; should be provided for all keys of 'web' kind
    #
    # Returns the Api Key object
    def create(options = {})
      res = @client.post('keys', options)
      res.to_h['key']
    end

    # Public: Delete Mailgun API key
    #
    # key_id - [String] The Key ID generated by Mailgun on key creation
    #
    # Returns a Boolean of the success
    def remove(key_id)
      @client.delete("keys/#{key_id}").status == 200
    end

    # Public: Regenerate Mailgun Public API key
    #
    # Returns new Mailgun Public API key.
    def regenerate
      res = @client.post('keys/public', {})
      res.to_h['key']
    end

    enforces_api_version 'v1', :list, :create, :remove, :regenerate
  end
end
