---
http_interactions:
- request:
    method: post
    uri: https://api.mailgun.net/v3/routes
    body:
      encoding: UTF-8
      string: action=forward%28%22.%2A%40%22%29&description=Integration+Test+Route&expression=match_recipient%28%22alice%40%22%29&priority=10
    headers:
      User-Agent:
      - mailgun-sdk-ruby/1.3.2
      Accept:
      - "*/*"
      Authorization:
      - Basic xxx==
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Length:
      - '251'
      Content-Type:
      - application/json
      Date:
      - Mon, 27 Jan 2025 17:45:19 GMT
      Server:
      - TwistedWeb/22.10.0
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Mailgun-Key-Id:
      - c02fd0ba-d8dbad66
      X-Xss-Protection:
      - 1; mode=block
    body:
      encoding: UTF-8
      string: '{"message":"Route has been created","route":{"actions":["forward(\".*@\")"],"created_at":"Mon,
        27 Jan 2025 17:45:19 GMT","description":"Integration Test Route","expression":"match_recipient(\"alice@\")","id":"6797c62f6ee0a9fcb1ec5eee","priority":10}}

        '
    http_version:
  recorded_at: Mon, 27 Jan 2025 17:45:19 GMT
- request:
    method: get
    uri: https://api.mailgun.net/v3/routes?limit=50
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - mailgun-sdk-ruby/1.3.2
      Accept:
      - "*/*"
      Authorization:
      - Basic xxx==
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Length:
      - '234'
      Content-Type:
      - application/json
      Date:
      - Mon, 27 Jan 2025 17:45:20 GMT
      Server:
      - TwistedWeb/22.10.0
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Mailgun-Key-Id:
      - c02fd0ba-d8dbad66
      X-Xss-Protection:
      - 1; mode=block
    body:
      encoding: UTF-8
      string: '{"items":[{"actions":["forward(\".*@\")"],"created_at":"Mon, 27 Jan
        2025 17:45:19 GMT","description":"Integration Test Route","expression":"match_recipient(\"alice@\")","id":"6797c62f6ee0a9fcb1ec5eee","priority":10}],"total_count":1}

        '
    http_version:
  recorded_at: Mon, 27 Jan 2025 17:45:20 GMT
- request:
    method: get
    uri: https://api.mailgun.net/v3/routes?limit=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - mailgun-sdk-ruby/1.3.2
      Accept:
      - "*/*"
      Authorization:
      - Basic xxx==
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Length:
      - '234'
      Content-Type:
      - application/json
      Date:
      - Mon, 27 Jan 2025 17:45:20 GMT
      Server:
      - TwistedWeb/22.10.0
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Mailgun-Key-Id:
      - c02fd0ba-d8dbad66
      X-Xss-Protection:
      - 1; mode=block
    body:
      encoding: UTF-8
      string: '{"items":[{"actions":["forward(\".*@\")"],"created_at":"Mon, 27 Jan
        2025 17:45:19 GMT","description":"Integration Test Route","expression":"match_recipient(\"alice@\")","id":"6797c62f6ee0a9fcb1ec5eee","priority":10}],"total_count":1}

        '
    http_version:
  recorded_at: Mon, 27 Jan 2025 17:45:20 GMT
- request:
    method: get
    uri: https://api.mailgun.net/v3/routes/6797c62f6ee0a9fcb1ec5eee
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - mailgun-sdk-ruby/1.3.2
      Accept:
      - "*/*"
      Authorization:
      - Basic xxx==
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Length:
      - '216'
      Content-Type:
      - application/json
      Date:
      - Mon, 27 Jan 2025 17:45:21 GMT
      Server:
      - TwistedWeb/22.10.0
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Mailgun-Key-Id:
      - c02fd0ba-d8dbad66
      X-Xss-Protection:
      - 1; mode=block
    body:
      encoding: UTF-8
      string: '{"route":{"actions":["forward(\".*@\")"],"created_at":"Mon, 27 Jan
        2025 17:45:19 GMT","description":"Integration Test Route","expression":"match_recipient(\"alice@\")","id":"6797c62f6ee0a9fcb1ec5eee","priority":10}}

        '
    http_version:
  recorded_at: Mon, 27 Jan 2025 17:45:21 GMT
- request:
    method: put
    uri: https://api.mailgun.net/v3/routes/6797c62f6ee0a9fcb1ec5eee
    body:
      encoding: UTF-8
      string: action=forward%28%22.%2A%40%22%29&description=Integration+Test+Route+Update&expression=match_recipient%28%22alice%40%22%29&priority=10
    headers:
      User-Agent:
      - mailgun-sdk-ruby/1.3.2
      Accept:
      - "*/*"
      Authorization:
      - Basic xxx==
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Length:
      - '248'
      Content-Type:
      - application/json
      Date:
      - Mon, 27 Jan 2025 17:45:22 GMT
      Server:
      - TwistedWeb/22.10.0
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Mailgun-Key-Id:
      - c02fd0ba-d8dbad66
      X-Xss-Protection:
      - 1; mode=block
    body:
      encoding: UTF-8
      string: '{"actions":["forward(\".*@\")"],"created_at":"Mon, 27 Jan 2025 17:45:19
        GMT","description":"Integration Test Route Update","expression":"match_recipient(\"alice@\")","id":"6797c62f6ee0a9fcb1ec5eee","message":"Route
        has been updated","priority":10}

        '
    http_version:
  recorded_at: Mon, 27 Jan 2025 17:45:22 GMT
- request:
    method: delete
    uri: https://api.mailgun.net/v3/routes/6797c62f6ee0a9fcb1ec5eee
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - mailgun-sdk-ruby/1.3.2
      Accept:
      - "*/*"
      Authorization:
      - Basic xxx==
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Length:
      - '69'
      Content-Type:
      - application/json
      Date:
      - Mon, 27 Jan 2025 17:45:22 GMT
      Server:
      - TwistedWeb/22.10.0
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Mailgun-Key-Id:
      - c02fd0ba-d8dbad66
      X-Xss-Protection:
      - 1; mode=block
    body:
      encoding: UTF-8
      string: '{"id":"6797c62f6ee0a9fcb1ec5eee","message":"Route has been deleted"}

        '
    http_version:
  recorded_at: Mon, 27 Jan 2025 17:45:23 GMT
- request:
    method: post
    uri: https://api.mailgun.net/v3/routes
    body:
      encoding: UTF-8
      string: action=forward%28%22.%2A%40%22%29&action=stop%28%29&description=Integration+Test+Route&expression=match_recipient%28%22alice%40%22%29&priority=10
    headers:
      User-Agent:
      - mailgun-sdk-ruby/1.3.2
      Accept:
      - "*/*"
      Authorization:
      - Basic xxx==
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Length:
      - '260'
      Content-Type:
      - application/json
      Date:
      - Mon, 27 Jan 2025 18:13:42 GMT
      Server:
      - TwistedWeb/22.10.0
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Mailgun-Key-Id:
      - c02fd0ba-d8dbad66
      X-Xss-Protection:
      - 1; mode=block
    body:
      encoding: UTF-8
      string: '{"message":"Route has been created","route":{"actions":["forward(\".*@\")","stop()"],"created_at":"Mon,
        27 Jan 2025 18:13:42 GMT","description":"Integration Test Route","expression":"match_recipient(\"alice@\")","id":"6797ccd69440716211d9df05","priority":10}}

        '
    http_version:
  recorded_at: Mon, 27 Jan 2025 18:13:42 GMT
recorded_with: VCR 3.0.3
