---
http_interactions:
- request:
    method: post
    uri: https://api.mailgun.net/v3/routes
    body:
      encoding: US-ASCII
      string: priority=10&description=Integration+Test+Route&expression=match_recipient%28%22alice%40DOMAIN.TEST%22%29&action=forward%28%22.*%40DOMAIN.TEST%22%29
    headers:
      Accept:
      - "*/*"
      User-Agent:
      - mailgun-sdk-ruby/1.2.6
      Content-Length:
      - '227'
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Host:
      - api.mailgun.net
      Authorization:
      - Basic <ENCODED_PRIVATE_KEY_AUTH>
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Content-Type, x-requested-with, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Max-Age:
      - '600'
      Cache-Control:
      - no-store
      Content-Type:
      - application/json
      Date:
      - Mon, 26 Jul 2021 17:43:55 GMT
      Server:
      - nginx
      Content-Length:
      - '402'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |-
        {
          "message": "Route has been created",
          "route": {
            "actions": [
              "forward(\".*@DOMAIN.TEST\")"
            ],
            "created_at": "Fri, 08 Jan 2016 20:08:18 GMT",
            "description": "Integration Test Route",
            "expression": "match_recipient(\"alice@DOMAIN.TEST\")",
            "id": "5690173212573000be30671e",
            "priority": 10
          }
        }
    http_version: 
  recorded_at: Mon, 26 Jul 2021 17:43:54 GMT
- request:
    method: get
    uri: https://api.mailgun.net/v3/routes?limit=50
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*"
      User-Agent:
      - mailgun-sdk-ruby/1.2.6
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Host:
      - api.mailgun.net
      Authorization:
      - Basic <ENCODED_PRIVATE_KEY_AUTH>
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, x-requested-with, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Max-Age:
      - '1155'
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Type:
      - application/json
      Date:
      - Mon, 26 Jul 2021 17:43:56 GMT
      Server:
      - nginx
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      Content-Length:
      - '37'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |-
        {
          "items": [
            {
              "actions": [
                "forward(\".*@DOMAIN.TEST\")"
              ],
              "created_at": "Fri, 08 Jan 2016 20:08:18 GMT",
              "description": "Integration Test Route",
              "expression": "match_recipient(\"alice@DOMAIN.TEST\")",
              "id": "5690173212573000be30671e",
              "priority": 10
            },
            {
              "actions": [
                "forward(\".*@DOMAIN.TEST\")"
              ],
              "created_at": "Fri, 08 Jan 2016 19:55:02 GMT",
              "description": "Integration Test Route",
              "expression": "match_recipient(\"alice@DOMAIN.TEST\")",
              "id": "5690141612573000b69c0e35",
              "priority": 10
            },
            {
              "actions": [
                "forward(\".*@DOMAIN.TEST\")"
              ],
              "created_at": "Fri, 08 Jan 2016 19:53:50 GMT",
              "description": "Integration Test Route",
              "expression": "match_recipient(\"alice@DOMAIN.TEST\")",
              "id": "569013ce11e2bdcea3fbcd1d",
              "priority": 10
            }
          ],
          "total_count": 3
        }
    http_version: 
  recorded_at: Mon, 26 Jul 2021 17:43:55 GMT
- request:
    method: get
    uri: https://api.mailgun.net/v3/routes?limit=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*"
      User-Agent:
      - mailgun-sdk-ruby/1.2.6
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Host:
      - api.mailgun.net
      Authorization:
      - Basic <ENCODED_PRIVATE_KEY_AUTH>
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - Content-Type, x-requested-with, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Max-Age:
      - '600'
      Cache-Control:
      - no-store
      Content-Disposition:
      - inline
      Content-Type:
      - application/json
      Date:
      - Mon, 26 Jul 2021 17:43:56 GMT
      Server:
      - nginx
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      Content-Length:
      - '37'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |-
        {
          "items": [
            {
              "actions": [
                "forward(\".*@DOMAIN.TEST\")"
              ],
              "created_at": "Fri, 08 Jan 2016 20:08:18 GMT",
              "description": "Integration Test Route",
              "expression": "match_recipient(\"alice@DOMAIN.TEST\")",
              "id": "5690173212573000be30671e",
              "priority": 10
            }
          ],
          "total_count": 3
        }
    http_version: 
  recorded_at: Mon, 26 Jul 2021 17:43:56 GMT
- request:
    method: get
    uri: https://api.mailgun.net/v3/routes/5690173212573000be30671e
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*"
      User-Agent:
      - mailgun-sdk-ruby/1.2.6
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Host:
      - api.mailgun.net
      Authorization:
      - Basic <ENCODED_PRIVATE_KEY_AUTH>
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Content-Type, x-requested-with, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Max-Age:
      - '600'
      Cache-Control:
      - no-store
      Content-Type:
      - application/json
      Date:
      - Mon, 26 Jul 2021 17:47:43 GMT
      Server:
      - nginx
      Content-Length:
      - '363'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |-
        {
          "route": {
            "actions": [
              "forward(\".*@DOMAIN.TEST\")"
            ],
            "created_at": "Fri, 08 Jan 2016 20:08:18 GMT",
            "description": "Integration Test Route",
            "expression": "match_recipient(\"alice@DOMAIN.TEST\")",
            "id": "5690173212573000be30671e",
            "priority": 10
          }
        }
    http_version: 
  recorded_at: Mon, 26 Jul 2021 17:47:43 GMT
- request:
    method: put
    uri: https://api.mailgun.net/v3/routes/5690173212573000be30671e
    body:
      encoding: US-ASCII
      string: priority=10&description=Integration+Test+Route+Update&expression=match_recipient%28%22alice%40DOMAIN.TEST%22%29&action=forward%28%22.*%40DOMAIN.TEST%22%29
    headers:
      Accept:
      - "*/*"
      User-Agent:
      - mailgun-sdk-ruby/1.2.6
      Content-Length:
      - '234'
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Host:
      - api.mailgun.net
      Authorization:
      - Basic <ENCODED_PRIVATE_KEY_AUTH>
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Content-Type, x-requested-with, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Max-Age:
      - '600'
      Cache-Control:
      - no-store
      Content-Type:
      - application/json
      Date:
      - Mon, 26 Jul 2021 17:47:44 GMT
      Server:
      - nginx
      Content-Length:
      - '376'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |-
        {
          "actions": [
            "forward(\".*@DOMAIN.TEST\")"
          ],
          "created_at": "Fri, 08 Jan 2016 20:08:18 GMT",
          "description": "Integration Test Route Update",
          "expression": "match_recipient(\"alice@DOMAIN.TEST\")",
          "id": "5690173212573000be30671e",
          "message": "Route has been updated",
          "priority": 10
        }
    http_version: 
  recorded_at: Mon, 26 Jul 2021 17:47:43 GMT
- request:
    method: delete
    uri: https://api.mailgun.net/v3/routes/5690173212573000be30671e
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*"
      User-Agent:
      - mailgun-sdk-ruby/1.2.6
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Host:
      - api.mailgun.net
      Authorization:
      - Basic <ENCODED_PRIVATE_KEY_AUTH>
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Content-Type, x-requested-with, Authorization
      Access-Control-Allow-Methods:
      - GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Max-Age:
      - '600'
      Cache-Control:
      - no-store
      Content-Type:
      - application/json
      Date:
      - Mon, 26 Jul 2021 17:47:44 GMT
      Server:
      - nginx
      Content-Length:
      - '34'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |-
        {
          "id": "5690173212573000be30671e",
          "message": "Route has been deleted"
        }
    http_version: 
  recorded_at: Mon, 26 Jul 2021 17:47:43 GMT
recorded_with: VCR 3.0.3
